version: '3.0'

services:
  app:
    build: ./
    restart: always
    networks:
      - traefik_default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50m'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app-wochenmenuplan.rule=Host(`app.wochenmenuplan.romix.ch`)'
      - 'traefik.http.routers.app-wochenmenuplan.entrypoints=websecure'
      - 'traefik.http.routers.app-wochenmenuplan.tls.certresolver=letsencrypt'

  build-hook:
    build: ./deployment/build-hook/
    restart: always
    volumes:
      - ./deployment/build-hook:/build-hook-server/build-hook
    networks:
      - traefik_default
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50m'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app-build-wochenmenuplan.rule=Host(`app-build.wochenmenuplan.romix.ch`)'
      - 'traefik.http.routers.app-build-wochenmenuplan.entrypoints=websecure'
      - 'traefik.http.routers.app-build-wochenmenuplan.tls.certresolver=letsencrypt'

networks:
  traefik_default:
    external: true

volumes:
  build-hook:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./deployment/build-hook
